apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: todo-list
  namespace: fission
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: nodeenv
    namespace: fission
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: app.todo
    packageref:
      name: todo-pkg
      namespace: fission
  requestsPerPod: 1
  resources: {}
  secrets:
    - name: mongodb-uri
      namespace: fission
