apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: create-route
  namespace: fission
spec:
  createingress: true
  functionref:
    functionweights: null
    name: todo-list
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /todos
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /todos
